jwt:
  secret: 984hg493gh0439thr0429guru2309yh937gc763fe87t3f89723gf
  lifetime: 20160m

spring:
  security:
    user:
      password: 528f3e4a-a7e8-44bc-a5b0-8c31ec0a95f7

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  application:
    name: streamifyAuth

server:
  port: 8080

