spring:

  security:
    user:
      password: 528f3e4a-a7e8-44bc-a5b0-8c31ec0a95f7

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB

  application:
    name: streamifyPost

server:
  port: 8081

connector:
  auth:
    url: http://localhost:8080/api/users

ssh:
  host: 192.168.0.180
  port: 22
  username: streamifyadmin
  password: 12345

