spring:
  security:
    user:
      password: 528f3e4a-a7e8-44bc-a5b0-8c31ec0a95f7

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/streamify_account
    username: streamify_account_admin
    password: I_PMr1Dbvke;QWE

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  application:
    name: streamifyFeed

connector:
  subscriptions:
    url: http://localhost:8080/api/users

server:
  port: 8083